/****************************************************************************
**
** Metadata for FiddlerCOM generated by dumpcpp from type library
** e:\QtProject_Git\a86b43fca89c33a2f703c0c6c7221cb8\FiddlerCOM\FiddlerCOM\bin\Release\FiddlerCOM.tlb
**
****************************************************************************/

#define QAX_DUMPCPP_FIDDLERCOM_NOINLINES
#include "fiddlercom.h"

using namespace FiddlerCOM;

struct qt_meta_stringdata_all_t {
    QByteArrayData data[39];
    char stringdata0[462];
};
#define QT_MOC_LITERAL(idx, ofs, len, table) \
    Q_STATIC_BYTE_ARRAY_DATA_HEADER_INITIALIZER_WITH_OFFSET(len, \
    offsetof(qt_meta_stringdata_all_t, stringdata##table) + ofs \
        - idx * sizeof(QByteArrayData) \
    )
static const qt_meta_stringdata_all_t qt_meta_stringdata_all = {
    {
QT_MOC_LITERAL(0, 0, 28, 0),
QT_MOC_LITERAL(1, 29, 9, 0),
QT_MOC_LITERAL(2, 39, 0, 0),
QT_MOC_LITERAL(3, 40, 4, 0),
QT_MOC_LITERAL(4, 45, 6, 0),
QT_MOC_LITERAL(5, 52, 4, 0),
QT_MOC_LITERAL(6, 57, 4, 0),
QT_MOC_LITERAL(7, 62, 15, 0),
QT_MOC_LITERAL(8, 78, 4, 0),
QT_MOC_LITERAL(9, 83, 6, 0),
QT_MOC_LITERAL(10, 90, 4, 0),
QT_MOC_LITERAL(11, 95, 4, 0),
QT_MOC_LITERAL(12, 100, 18, 0),
QT_MOC_LITERAL(13, 119, 8, 0),
QT_MOC_LITERAL(14, 128, 7, 0),
QT_MOC_LITERAL(15, 136, 6, 0),
QT_MOC_LITERAL(16, 143, 23, 0),
QT_MOC_LITERAL(17, 167, 1, 0),
QT_MOC_LITERAL(18, 169, 16, 0),
QT_MOC_LITERAL(19, 186, 17, 0),
QT_MOC_LITERAL(20, 204, 14, 0),
QT_MOC_LITERAL(21, 219, 17, 0),
QT_MOC_LITERAL(22, 237, 16, 0),
QT_MOC_LITERAL(23, 254, 8, 0),
QT_MOC_LITERAL(24, 263, 7, 0),
QT_MOC_LITERAL(25, 271, 11, 0),
QT_MOC_LITERAL(26, 283, 22, 0),
QT_MOC_LITERAL(27, 306, 11, 0),
QT_MOC_LITERAL(28, 318, 20, 0),
QT_MOC_LITERAL(29, 339, 7, 0),
QT_MOC_LITERAL(30, 347, 27, 0),
QT_MOC_LITERAL(31, 375, 11, 0),
QT_MOC_LITERAL(32, 387, 16, 0),
QT_MOC_LITERAL(33, 404, 6, 0),
QT_MOC_LITERAL(34, 411, 3, 0),
QT_MOC_LITERAL(35, 415, 11, 0),
QT_MOC_LITERAL(36, 427, 7, 0),
QT_MOC_LITERAL(37, 435, 16, 0),
QT_MOC_LITERAL(38, 452, 8, 0)
    },
    "FiddlerCOM::IFiddlerComClass\0exception\0\0code\0source\0disc\0help\0propertyChanged\0"
    "name\0signal\0argc\0argv\0InstallCertificate\0QString&\0certStr\0keyStr\0"
    "SetAfterSessionComplete\0f\0SetBeforeRequest\0SetBeforeResponse\0SetOnLogString\0"
    "SetOnNotification\0SetupCertificate\0Shutdown\0Startup\0iListenPort\0"
    "bRegisterAsSystemProxy\0bDecryptSSL\0UninstallCertificate\0control\0"
    "FiddlerCOM::FiddlerCOMClass\0Interface 1\0IFiddlerComClass\0Equals\0obj\0GetHashCode\0"
    "GetType\0mscorlib::_Type*\0ToString\0"
};
#undef QT_MOC_LITERAL

static const uint qt_meta_data_FiddlerCOM__IFiddlerComClass[] = {

 // content:
    7, // revision
    0,  // classname
    0, 0, // classinfo
    13, 14, // methods
    1, 136, // properties
    0, 0, // enums/sets
    0, 0, // constructors
    0, // flags
    3, // signal count

// signal: name, argc, parameters, tag, flags
    1, 4, 79, 2, 5,
    7, 1, 88, 2, 5,
    9, 3, 91, 2, 5,

// slot: name, argc, parameters, tag, flags
    12, 2, 98, 2, 9,
    16, 1, 103, 2, 9,
    18, 1, 106, 2, 9,
    19, 1, 109, 2, 9,
    20, 1, 112, 2, 9,
    21, 1, 115, 2, 9,
    22, 2, 118, 2, 9,
    23, 0, 123, 2, 9,
    24, 3, 124, 2, 9,
    28, 2, 131, 2, 9,

// signal: parameters
    QMetaType::Void, QMetaType::Int, QMetaType::QString, QMetaType::QString, QMetaType::QString, 3, 4, 5, 6,
    QMetaType::Void, QMetaType::QString, 8,
    QMetaType::Void, QMetaType::QString, QMetaType::Int, QMetaType::VoidStar, 8, 10, 11,

// slot: parameters
    QMetaType::Bool, 0x80000000 | 13, 0x80000000 | 13, 14, 15,
    QMetaType::Void, QMetaType::Int, 17,
    QMetaType::Void, QMetaType::Int, 17,
    QMetaType::Void, QMetaType::Int, 17,
    QMetaType::Void, QMetaType::Int, 17,
    QMetaType::Void, QMetaType::Int, 17,
    QMetaType::Void, QMetaType::QString, QMetaType::QString, 14, 15,
    QMetaType::Void,
    QMetaType::Void, QMetaType::Int, QMetaType::Bool, QMetaType::Bool, 25, 26, 27,
    QMetaType::Bool, 0x80000000 | 13, 0x80000000 | 13, 14, 15,

 // properties: name, type, flags
    29, QMetaType::QString, 0x0a055003, 		 // QString control

    0 // eod
};

const QMetaObject IFiddlerComClass::staticMetaObject = {
{ &QObject::staticMetaObject,
qt_meta_stringdata_all.data,
qt_meta_data_FiddlerCOM__IFiddlerComClass, 0, 0, 0 }
};

void *IFiddlerComClass::qt_metacast(const char *_clname)
{
    if (!_clname) return 0;
    if (!strcmp(_clname, "FiddlerCOM::IFiddlerComClass"))
        return static_cast<void*>(const_cast<IFiddlerComClass*>(this));
    return QAxObject::qt_metacast(_clname);
}
static const uint qt_meta_data_FiddlerCOM__FiddlerCOMClass[] = {

 // content:
    7, // revision
    30,  // classname
    1, 14, // classinfo
    16, 16, // methods
    1, 158, // properties
    0, 0, // enums/sets
    0, 0, // constructors
    0, // flags
    3, // signal count

 // classinfo: key, value
    31, 32, 

// signal: name, argc, parameters, tag, flags
    1, 4, 96, 2, 5,
    7, 1, 105, 2, 5,
    9, 3, 108, 2, 5,

// slot: name, argc, parameters, tag, flags
    33, 1, 115, 2, 9,
    35, 0, 118, 2, 9,
    36, 0, 119, 2, 9,
    12, 2, 120, 2, 9,
    16, 1, 125, 2, 9,
    18, 1, 128, 2, 9,
    19, 1, 131, 2, 9,
    20, 1, 134, 2, 9,
    21, 1, 137, 2, 9,
    22, 2, 140, 2, 9,
    23, 0, 145, 2, 9,
    24, 3, 146, 2, 9,
    28, 2, 153, 2, 9,

// signal: parameters
    QMetaType::Void, QMetaType::Int, QMetaType::QString, QMetaType::QString, QMetaType::QString, 3, 4, 5, 6,
    QMetaType::Void, QMetaType::QString, 8,
    QMetaType::Void, QMetaType::QString, QMetaType::Int, QMetaType::VoidStar, 8, 10, 11,

// slot: parameters
    QMetaType::Bool, QMetaType::QVariant, 34,
    QMetaType::Int,
    0x80000000 | 37,
    QMetaType::Bool, 0x80000000 | 13, 0x80000000 | 13, 14, 15,
    QMetaType::Void, QMetaType::Int, 17,
    QMetaType::Void, QMetaType::Int, 17,
    QMetaType::Void, QMetaType::Int, 17,
    QMetaType::Void, QMetaType::Int, 17,
    QMetaType::Void, QMetaType::Int, 17,
    QMetaType::Void, QMetaType::QString, QMetaType::QString, 14, 15,
    QMetaType::Void,
    QMetaType::Void, QMetaType::Int, QMetaType::Bool, QMetaType::Bool, 25, 26, 27,
    QMetaType::Bool, 0x80000000 | 13, 0x80000000 | 13, 14, 15,

 // properties: name, type, flags
    38, QMetaType::QString, 0x0a005001, 		 // QString ToString

    0 // eod
};

const QMetaObject FiddlerCOMClass::staticMetaObject = {
{ &QObject::staticMetaObject,
qt_meta_stringdata_all.data,
qt_meta_data_FiddlerCOM__FiddlerCOMClass, 0, 0, 0 }
};

void *FiddlerCOMClass::qt_metacast(const char *_clname)
{
    if (!_clname) return 0;
    if (!strcmp(_clname, "FiddlerCOM::FiddlerCOMClass"))
        return static_cast<void*>(const_cast<FiddlerCOMClass*>(this));
    return QAxObject::qt_metacast(_clname);
}

