/****************************************************************************
**
** Metadata for FiddlerCOM generated by dumpcpp from type library
** C:\Users\h5nc\Documents\Visual Studio 2013\Projects\FiddlerCOM\FiddlerCOM\bin\Release\FiddlerCOM.tlb
**
****************************************************************************/

#define QAX_DUMPCPP_FIDDLERCOM_NOINLINES
#include "FiddlerCOM.h"

using namespace FiddlerCOM;

struct qt_meta_stringdata_all_t {
    QByteArrayData data[33];
    char stringdata0[381];
};
#define QT_MOC_LITERAL(idx, ofs, len, table) \
    Q_STATIC_BYTE_ARRAY_DATA_HEADER_INITIALIZER_WITH_OFFSET(len, \
    offsetof(qt_meta_stringdata_all_t, stringdata##table) + ofs \
        - idx * sizeof(QByteArrayData) \
    )
static const qt_meta_stringdata_all_t qt_meta_stringdata_all = {
    {
QT_MOC_LITERAL(0, 0, 28, 0),
QT_MOC_LITERAL(1, 29, 9, 0),
QT_MOC_LITERAL(2, 39, 0, 0),
QT_MOC_LITERAL(3, 40, 4, 0),
QT_MOC_LITERAL(4, 45, 6, 0),
QT_MOC_LITERAL(5, 52, 4, 0),
QT_MOC_LITERAL(6, 57, 4, 0),
QT_MOC_LITERAL(7, 62, 15, 0),
QT_MOC_LITERAL(8, 78, 4, 0),
QT_MOC_LITERAL(9, 83, 6, 0),
QT_MOC_LITERAL(10, 90, 4, 0),
QT_MOC_LITERAL(11, 95, 4, 0),
QT_MOC_LITERAL(12, 100, 23, 0),
QT_MOC_LITERAL(13, 124, 1, 0),
QT_MOC_LITERAL(14, 126, 16, 0),
QT_MOC_LITERAL(15, 143, 17, 0),
QT_MOC_LITERAL(16, 161, 14, 0),
QT_MOC_LITERAL(17, 176, 17, 0),
QT_MOC_LITERAL(18, 194, 8, 0),
QT_MOC_LITERAL(19, 203, 7, 0),
QT_MOC_LITERAL(20, 211, 11, 0),
QT_MOC_LITERAL(21, 223, 22, 0),
QT_MOC_LITERAL(22, 246, 11, 0),
QT_MOC_LITERAL(23, 258, 7, 0),
QT_MOC_LITERAL(24, 266, 27, 0),
QT_MOC_LITERAL(25, 294, 11, 0),
QT_MOC_LITERAL(26, 306, 16, 0),
QT_MOC_LITERAL(27, 323, 6, 0),
QT_MOC_LITERAL(28, 330, 3, 0),
QT_MOC_LITERAL(29, 334, 11, 0),
QT_MOC_LITERAL(30, 346, 7, 0),
QT_MOC_LITERAL(31, 354, 16, 0),
QT_MOC_LITERAL(32, 371, 8, 0)
    },
    "FiddlerCOM::IFiddlerComClass\0exception\0\0code\0source\0disc\0help\0propertyChanged\0"
    "name\0signal\0argc\0argv\0SetAfterSessionComplete\0f\0SetBeforeRequest\0SetBeforeResponse\0"
    "SetOnLogString\0SetOnNotification\0Shutdown\0Startup\0iListenPort\0bRegisterAsSystemProxy\0"
    "bDecryptSSL\0control\0FiddlerCOM::FiddlerCOMClass\0Interface 1\0IFiddlerComClass\0"
    "Equals\0obj\0GetHashCode\0GetType\0mscorlib::_Type*\0ToString\0"
};
#undef QT_MOC_LITERAL

static const uint qt_meta_data_FiddlerCOM__IFiddlerComClass[] = {

 // content:
    7, // revision
    0,  // classname
    0, 0, // classinfo
    10, 14, // methods
    1, 106, // properties
    0, 0, // enums/sets
    0, 0, // constructors
    0, // flags
    3, // signal count

// signal: name, argc, parameters, tag, flags
    1, 4, 64, 2, 5,
    7, 1, 73, 2, 5,
    9, 3, 76, 2, 5,

// slot: name, argc, parameters, tag, flags
    12, 1, 83, 2, 9,
    14, 1, 86, 2, 9,
    15, 1, 89, 2, 9,
    16, 1, 92, 2, 9,
    17, 1, 95, 2, 9,
    18, 0, 98, 2, 9,
    19, 3, 99, 2, 9,

// signal: parameters
    QMetaType::Void, QMetaType::Int, QMetaType::QString, QMetaType::QString, QMetaType::QString, 3, 4, 5, 6,
    QMetaType::Void, QMetaType::QString, 8,
    QMetaType::Void, QMetaType::QString, QMetaType::Int, QMetaType::VoidStar, 8, 10, 11,

// slot: parameters
    QMetaType::Void, QMetaType::Int, 13,
    QMetaType::Void, QMetaType::Int, 13,
    QMetaType::Void, QMetaType::Int, 13,
    QMetaType::Void, QMetaType::Int, 13,
    QMetaType::Void, QMetaType::Int, 13,
    QMetaType::Void,
    QMetaType::Void, QMetaType::Int, QMetaType::Bool, QMetaType::Bool, 20, 21, 22,

 // properties: name, type, flags
    23, QMetaType::QString, 0x0a055003, 		 // QString control

    0 // eod
};

const QMetaObject IFiddlerComClass::staticMetaObject = {
{ &QObject::staticMetaObject,
qt_meta_stringdata_all.data,
qt_meta_data_FiddlerCOM__IFiddlerComClass, 0, 0, 0 }
};

void *IFiddlerComClass::qt_metacast(const char *_clname)
{
    if (!_clname) return 0;
    if (!strcmp(_clname, "FiddlerCOM::IFiddlerComClass"))
        return static_cast<void*>(const_cast<IFiddlerComClass*>(this));
    return QAxObject::qt_metacast(_clname);
}
static const uint qt_meta_data_FiddlerCOM__FiddlerCOMClass[] = {

 // content:
    7, // revision
    24,  // classname
    1, 14, // classinfo
    13, 16, // methods
    1, 128, // properties
    0, 0, // enums/sets
    0, 0, // constructors
    0, // flags
    3, // signal count

 // classinfo: key, value
    25, 26, 

// signal: name, argc, parameters, tag, flags
    1, 4, 81, 2, 5,
    7, 1, 90, 2, 5,
    9, 3, 93, 2, 5,

// slot: name, argc, parameters, tag, flags
    27, 1, 100, 2, 9,
    29, 0, 103, 2, 9,
    30, 0, 104, 2, 9,
    12, 1, 105, 2, 9,
    14, 1, 108, 2, 9,
    15, 1, 111, 2, 9,
    16, 1, 114, 2, 9,
    17, 1, 117, 2, 9,
    18, 0, 120, 2, 9,
    19, 3, 121, 2, 9,

// signal: parameters
    QMetaType::Void, QMetaType::Int, QMetaType::QString, QMetaType::QString, QMetaType::QString, 3, 4, 5, 6,
    QMetaType::Void, QMetaType::QString, 8,
    QMetaType::Void, QMetaType::QString, QMetaType::Int, QMetaType::VoidStar, 8, 10, 11,

// slot: parameters
    QMetaType::Bool, QMetaType::QVariant, 28,
    QMetaType::Int,
    0x80000000 | 31,
    QMetaType::Void, QMetaType::Int, 13,
    QMetaType::Void, QMetaType::Int, 13,
    QMetaType::Void, QMetaType::Int, 13,
    QMetaType::Void, QMetaType::Int, 13,
    QMetaType::Void, QMetaType::Int, 13,
    QMetaType::Void,
    QMetaType::Void, QMetaType::Int, QMetaType::Bool, QMetaType::Bool, 20, 21, 22,

 // properties: name, type, flags
    32, QMetaType::QString, 0x0a005001, 		 // QString ToString

    0 // eod
};

const QMetaObject FiddlerCOMClass::staticMetaObject = {
{ &QObject::staticMetaObject,
qt_meta_stringdata_all.data,
qt_meta_data_FiddlerCOM__FiddlerCOMClass, 0, 0, 0 }
};

void *FiddlerCOMClass::qt_metacast(const char *_clname)
{
    if (!_clname) return 0;
    if (!strcmp(_clname, "FiddlerCOM::FiddlerCOMClass"))
        return static_cast<void*>(const_cast<FiddlerCOMClass*>(this));
    return QAxObject::qt_metacast(_clname);
}

