/****************************************************************************
**
** Namespace Nekoxy generated by dumpcpp from type library
** e:\QtProject_Git\a86b43fca89c33a2f703c0c6c7221cb8\Nekoxy\Nekoxy\bin\Release\Nekoxy.tlb
**
****************************************************************************/

#ifndef QAX_DUMPCPP_NEKOXY_H
#define QAX_DUMPCPP_NEKOXY_H

// Define this symbol to __declspec(dllexport) or __declspec(dllimport)
#ifndef NEKOXY_EXPORT
#define NEKOXY_EXPORT
#endif

#include <qaxobject.h>
#include <qaxwidget.h>
#include <qdatetime.h>
#include <qpixmap.h>

struct IDispatch;


// Referenced namespace
namespace mscorlib {
    class _Type;
}


namespace Nekoxy {


class NEKOXY_EXPORT INekoxyClass : public QAxObject
{
public:
    INekoxyClass(IDispatch *subobject = 0, QAxObject *parent = 0)
    : QAxObject((IUnknown*)subobject, parent)
    {
        internalRelease();
    }

    /*
    Method InstallCertificate
    */
    inline bool InstallCertificate(QString& certStr, QString& keyStr);

    /*
    Method SetAfterSessionComplete
    */
    inline void SetAfterSessionComplete(int f);

    /*
    Method SetBeforeRequest
    */
    inline void SetBeforeRequest(int f);

    /*
    Method SetBeforeResponse
    */
    inline void SetBeforeResponse(int f);

    /*
    Method SetOnLogString
    */
    inline void SetOnLogString(int f);

    /*
    Method SetOnNotification
    */
    inline void SetOnNotification(int f);

    /*
    Method SetupCertificate
    */
    inline void SetupCertificate(const QString& certStr, const QString& keyStr);

    /*
    Method Shutdown
    */
    inline void Shutdown();

    /*
    Method Startup
    */
    inline void Startup(int iListenPort, bool bRegisterAsSystemProxy, bool bDecryptSSL);

    /*
    Method UninstallCertificate
    */
    inline bool UninstallCertificate(QString& certStr, QString& keyStr);

// meta object functions
    static const QMetaObject staticMetaObject;
    virtual const QMetaObject *metaObject() const { return &staticMetaObject; }
    virtual void *qt_metacast(const char *);
};

// Actual coclasses
class NEKOXY_EXPORT HttpProxy : public QAxObject
{
public:
    HttpProxy(QObject *parent = 0)
    : QAxObject(parent)
    {
        setControl("{ea5a138c-1947-3999-abad-6a055827be15}");
    }

    HttpProxy(INekoxyClass *iface)
    : QAxObject()
    {
        initializeFrom(iface);
        delete iface;
    }

    /*
    Property ToString
    */
    inline QString ToString() const; //Returns the value of ToString

    /*
    Method Equals
    */
    inline bool Equals(const QVariant& obj);

    /*
    Method GetHashCode
    */
    inline int GetHashCode();

    /*
    Method GetType
    */
    inline mscorlib::_Type* GetType();

    /*
    Method InstallCertificate
    */
    inline bool InstallCertificate(QString& certStr, QString& keyStr);

    /*
    Method SetAfterSessionComplete
    */
    inline void SetAfterSessionComplete(int f);

    /*
    Method SetBeforeRequest
    */
    inline void SetBeforeRequest(int f);

    /*
    Method SetBeforeResponse
    */
    inline void SetBeforeResponse(int f);

    /*
    Method SetOnLogString
    */
    inline void SetOnLogString(int f);

    /*
    Method SetOnNotification
    */
    inline void SetOnNotification(int f);

    /*
    Method SetupCertificate
    */
    inline void SetupCertificate(const QString& certStr, const QString& keyStr);

    /*
    Method Shutdown
    */
    inline void Shutdown();

    /*
    Method Startup
    */
    inline void Startup(int iListenPort, bool bRegisterAsSystemProxy, bool bDecryptSSL);

    /*
    Method UninstallCertificate
    */
    inline bool UninstallCertificate(QString& certStr, QString& keyStr);

// meta object functions
    static const QMetaObject staticMetaObject;
    virtual const QMetaObject *metaObject() const { return &staticMetaObject; }
    virtual void *qt_metacast(const char *);
};

// member function implementation
#ifndef QAX_DUMPCPP_NEKOXY_NOINLINES
inline bool INekoxyClass::InstallCertificate(QString& certStr, QString& keyStr)
{
    bool qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&certStr, (void*)&keyStr};
    qt_metacall(QMetaObject::InvokeMetaMethod, 8, _a);
    return qax_result;
}

inline void INekoxyClass::SetAfterSessionComplete(int f)
{
    void *_a[] = {0, (void*)&f};
    qt_metacall(QMetaObject::InvokeMetaMethod, 9, _a);
}

inline void INekoxyClass::SetBeforeRequest(int f)
{
    void *_a[] = {0, (void*)&f};
    qt_metacall(QMetaObject::InvokeMetaMethod, 10, _a);
}

inline void INekoxyClass::SetBeforeResponse(int f)
{
    void *_a[] = {0, (void*)&f};
    qt_metacall(QMetaObject::InvokeMetaMethod, 11, _a);
}

inline void INekoxyClass::SetOnLogString(int f)
{
    void *_a[] = {0, (void*)&f};
    qt_metacall(QMetaObject::InvokeMetaMethod, 12, _a);
}

inline void INekoxyClass::SetOnNotification(int f)
{
    void *_a[] = {0, (void*)&f};
    qt_metacall(QMetaObject::InvokeMetaMethod, 13, _a);
}

inline void INekoxyClass::SetupCertificate(const QString& certStr, const QString& keyStr)
{
    void *_a[] = {0, (void*)&certStr, (void*)&keyStr};
    qt_metacall(QMetaObject::InvokeMetaMethod, 14, _a);
}

inline void INekoxyClass::Shutdown()
{
    void *_a[] = {0};
    qt_metacall(QMetaObject::InvokeMetaMethod, 15, _a);
}

inline void INekoxyClass::Startup(int iListenPort, bool bRegisterAsSystemProxy, bool bDecryptSSL)
{
    void *_a[] = {0, (void*)&iListenPort, (void*)&bRegisterAsSystemProxy, (void*)&bDecryptSSL};
    qt_metacall(QMetaObject::InvokeMetaMethod, 16, _a);
}

inline bool INekoxyClass::UninstallCertificate(QString& certStr, QString& keyStr)
{
    bool qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&certStr, (void*)&keyStr};
    qt_metacall(QMetaObject::InvokeMetaMethod, 17, _a);
    return qax_result;
}


inline QString HttpProxy::ToString() const
{
    QVariant qax_result = property("ToString");
    Q_ASSERT(qax_result.isValid());
    return *(QString*)qax_result.constData();
}

inline bool HttpProxy::Equals(const QVariant& obj)
{
    bool qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&obj};
    qt_metacall(QMetaObject::InvokeMetaMethod, 8, _a);
    return qax_result;
}

inline int HttpProxy::GetHashCode()
{
    int qax_result;
    void *_a[] = {(void*)&qax_result};
    qt_metacall(QMetaObject::InvokeMetaMethod, 9, _a);
    return qax_result;
}

inline mscorlib::_Type* HttpProxy::GetType()
{
    mscorlib::_Type* qax_result = 0;
#ifdef QAX_DUMPCPP_MSCORLIB_H
    qRegisterMetaType<mscorlib::_Type*>("mscorlib::_Type*", &qax_result);
    qRegisterMetaType<mscorlib::_Type>("mscorlib::_Type", qax_result);
#endif
    void *_a[] = {(void*)&qax_result};
    qt_metacall(QMetaObject::InvokeMetaMethod, 10, _a);
    return qax_result;
}

inline bool HttpProxy::InstallCertificate(QString& certStr, QString& keyStr)
{
    bool qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&certStr, (void*)&keyStr};
    qt_metacall(QMetaObject::InvokeMetaMethod, 11, _a);
    return qax_result;
}

inline void HttpProxy::SetAfterSessionComplete(int f)
{
    void *_a[] = {0, (void*)&f};
    qt_metacall(QMetaObject::InvokeMetaMethod, 12, _a);
}

inline void HttpProxy::SetBeforeRequest(int f)
{
    void *_a[] = {0, (void*)&f};
    qt_metacall(QMetaObject::InvokeMetaMethod, 13, _a);
}

inline void HttpProxy::SetBeforeResponse(int f)
{
    void *_a[] = {0, (void*)&f};
    qt_metacall(QMetaObject::InvokeMetaMethod, 14, _a);
}

inline void HttpProxy::SetOnLogString(int f)
{
    void *_a[] = {0, (void*)&f};
    qt_metacall(QMetaObject::InvokeMetaMethod, 15, _a);
}

inline void HttpProxy::SetOnNotification(int f)
{
    void *_a[] = {0, (void*)&f};
    qt_metacall(QMetaObject::InvokeMetaMethod, 16, _a);
}

inline void HttpProxy::SetupCertificate(const QString& certStr, const QString& keyStr)
{
    void *_a[] = {0, (void*)&certStr, (void*)&keyStr};
    qt_metacall(QMetaObject::InvokeMetaMethod, 17, _a);
}

inline void HttpProxy::Shutdown()
{
    void *_a[] = {0};
    qt_metacall(QMetaObject::InvokeMetaMethod, 18, _a);
}

inline void HttpProxy::Startup(int iListenPort, bool bRegisterAsSystemProxy, bool bDecryptSSL)
{
    void *_a[] = {0, (void*)&iListenPort, (void*)&bRegisterAsSystemProxy, (void*)&bDecryptSSL};
    qt_metacall(QMetaObject::InvokeMetaMethod, 19, _a);
}

inline bool HttpProxy::UninstallCertificate(QString& certStr, QString& keyStr)
{
    bool qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&certStr, (void*)&keyStr};
    qt_metacall(QMetaObject::InvokeMetaMethod, 20, _a);
    return qax_result;
}



#endif

}

QT_BEGIN_NAMESPACE

namespace QtMetaTypePrivate {
template<>
struct QMetaTypeFunctionHelper<Nekoxy::INekoxyClass, /* Accepted */ true> {
    static void Delete(void *t) { delete static_cast<Nekoxy::INekoxyClass*>(t); }
    static void *Create(const void *t)
    {
        Q_ASSERT(!t);
        Q_UNUSED(t)
        return new Nekoxy::INekoxyClass();
    }
    static void Destruct(void *t)
    {
        Q_UNUSED(t)
        static_cast<Nekoxy::INekoxyClass*>(t)->Nekoxy::INekoxyClass::~INekoxyClass();
    }
    static void *Construct(void *where, const void *t)
    {
        Q_ASSERT(!t);
        Q_UNUSED(t)
        return new (where) Nekoxy::INekoxyClass;
    }
#ifndef QT_NO_DATASTREAM
    static void Save(QDataStream &stream, const void *t) { stream << *static_cast<const Nekoxy::INekoxyClass*>(t); }
    static void Load(QDataStream &stream, void *t) { stream >> *static_cast<Nekoxy::INekoxyClass*>(t); }
#endif // QT_NO_DATASTREAM
};

template<>
struct QMetaTypeFunctionHelper<Nekoxy::HttpProxy, /* Accepted */ true> {
    static void Delete(void *t) { delete static_cast<Nekoxy::HttpProxy*>(t); }
    static void *Create(const void *t)
    {
        Q_ASSERT(!t);
        Q_UNUSED(t)
        return new Nekoxy::HttpProxy();
    }
    static void Destruct(void *t)
    {
        Q_UNUSED(t)
        static_cast<Nekoxy::HttpProxy*>(t)->Nekoxy::HttpProxy::~HttpProxy();
    }
    static void *Construct(void *where, const void *t)
    {
        Q_ASSERT(!t);
        Q_UNUSED(t)
        return new (where) Nekoxy::HttpProxy;
    }
#ifndef QT_NO_DATASTREAM
    static void Save(QDataStream &stream, const void *t) { stream << *static_cast<const Nekoxy::HttpProxy*>(t); }
    static void Load(QDataStream &stream, void *t) { stream >> *static_cast<Nekoxy::HttpProxy*>(t); }
#endif // QT_NO_DATASTREAM
};

} // namespace QtMetaTypePrivate
QT_END_NAMESPACE

#endif

