/****************************************************************************
**
** Metadata for Nekoxy generated by dumpcpp from type library
** e:\QtProject_Git\a86b43fca89c33a2f703c0c6c7221cb8\Nekoxy\Nekoxy\bin\Release\Nekoxy.tlb
**
****************************************************************************/

#define QAX_DUMPCPP_NEKOXY_NOINLINES
#include "nekoxy.h"

using namespace Nekoxy;

struct qt_meta_stringdata_all_t {
    QByteArrayData data[39];
    char stringdata0[440];
};
#define QT_MOC_LITERAL(idx, ofs, len, table) \
    Q_STATIC_BYTE_ARRAY_DATA_HEADER_INITIALIZER_WITH_OFFSET(len, \
    offsetof(qt_meta_stringdata_all_t, stringdata##table) + ofs \
        - idx * sizeof(QByteArrayData) \
    )
static const qt_meta_stringdata_all_t qt_meta_stringdata_all = {
    {
QT_MOC_LITERAL(0, 0, 20, 0),
QT_MOC_LITERAL(1, 21, 9, 0),
QT_MOC_LITERAL(2, 31, 0, 0),
QT_MOC_LITERAL(3, 32, 4, 0),
QT_MOC_LITERAL(4, 37, 6, 0),
QT_MOC_LITERAL(5, 44, 4, 0),
QT_MOC_LITERAL(6, 49, 4, 0),
QT_MOC_LITERAL(7, 54, 15, 0),
QT_MOC_LITERAL(8, 70, 4, 0),
QT_MOC_LITERAL(9, 75, 6, 0),
QT_MOC_LITERAL(10, 82, 4, 0),
QT_MOC_LITERAL(11, 87, 4, 0),
QT_MOC_LITERAL(12, 92, 18, 0),
QT_MOC_LITERAL(13, 111, 8, 0),
QT_MOC_LITERAL(14, 120, 7, 0),
QT_MOC_LITERAL(15, 128, 6, 0),
QT_MOC_LITERAL(16, 135, 23, 0),
QT_MOC_LITERAL(17, 159, 1, 0),
QT_MOC_LITERAL(18, 161, 16, 0),
QT_MOC_LITERAL(19, 178, 17, 0),
QT_MOC_LITERAL(20, 196, 14, 0),
QT_MOC_LITERAL(21, 211, 17, 0),
QT_MOC_LITERAL(22, 229, 16, 0),
QT_MOC_LITERAL(23, 246, 8, 0),
QT_MOC_LITERAL(24, 255, 7, 0),
QT_MOC_LITERAL(25, 263, 11, 0),
QT_MOC_LITERAL(26, 275, 22, 0),
QT_MOC_LITERAL(27, 298, 11, 0),
QT_MOC_LITERAL(28, 310, 20, 0),
QT_MOC_LITERAL(29, 331, 7, 0),
QT_MOC_LITERAL(30, 339, 17, 0),
QT_MOC_LITERAL(31, 357, 11, 0),
QT_MOC_LITERAL(32, 369, 12, 0),
QT_MOC_LITERAL(33, 382, 6, 0),
QT_MOC_LITERAL(34, 389, 3, 0),
QT_MOC_LITERAL(35, 393, 11, 0),
QT_MOC_LITERAL(36, 405, 7, 0),
QT_MOC_LITERAL(37, 413, 16, 0),
QT_MOC_LITERAL(38, 430, 8, 0)
    },
    "Nekoxy::INekoxyClass\0exception\0\0code\0source\0disc\0help\0propertyChanged\0name\0"
    "signal\0argc\0argv\0InstallCertificate\0QString&\0certStr\0keyStr\0SetAfterSessionComplete\0"
    "f\0SetBeforeRequest\0SetBeforeResponse\0SetOnLogString\0SetOnNotification\0"
    "SetupCertificate\0Shutdown\0Startup\0iListenPort\0bRegisterAsSystemProxy\0bDecryptSSL\0"
    "UninstallCertificate\0control\0Nekoxy::HttpProxy\0Interface 1\0INekoxyClass\0"
    "Equals\0obj\0GetHashCode\0GetType\0mscorlib::_Type*\0ToString\0"
};
#undef QT_MOC_LITERAL

static const uint qt_meta_data_Nekoxy__INekoxyClass[] = {

 // content:
    7, // revision
    0,  // classname
    0, 0, // classinfo
    13, 14, // methods
    1, 136, // properties
    0, 0, // enums/sets
    0, 0, // constructors
    0, // flags
    3, // signal count

// signal: name, argc, parameters, tag, flags
    1, 4, 79, 2, 5,
    7, 1, 88, 2, 5,
    9, 3, 91, 2, 5,

// slot: name, argc, parameters, tag, flags
    12, 2, 98, 2, 9,
    16, 1, 103, 2, 9,
    18, 1, 106, 2, 9,
    19, 1, 109, 2, 9,
    20, 1, 112, 2, 9,
    21, 1, 115, 2, 9,
    22, 2, 118, 2, 9,
    23, 0, 123, 2, 9,
    24, 3, 124, 2, 9,
    28, 2, 131, 2, 9,

// signal: parameters
    QMetaType::Void, QMetaType::Int, QMetaType::QString, QMetaType::QString, QMetaType::QString, 3, 4, 5, 6,
    QMetaType::Void, QMetaType::QString, 8,
    QMetaType::Void, QMetaType::QString, QMetaType::Int, QMetaType::VoidStar, 8, 10, 11,

// slot: parameters
    QMetaType::Bool, 0x80000000 | 13, 0x80000000 | 13, 14, 15,
    QMetaType::Void, QMetaType::Int, 17,
    QMetaType::Void, QMetaType::Int, 17,
    QMetaType::Void, QMetaType::Int, 17,
    QMetaType::Void, QMetaType::Int, 17,
    QMetaType::Void, QMetaType::Int, 17,
    QMetaType::Void, QMetaType::QString, QMetaType::QString, 14, 15,
    QMetaType::Void,
    QMetaType::Void, QMetaType::Int, QMetaType::Bool, QMetaType::Bool, 25, 26, 27,
    QMetaType::Bool, 0x80000000 | 13, 0x80000000 | 13, 14, 15,

 // properties: name, type, flags
    29, QMetaType::QString, 0x0a055003, 		 // QString control

    0 // eod
};

const QMetaObject INekoxyClass::staticMetaObject = {
{ &QObject::staticMetaObject,
qt_meta_stringdata_all.data,
qt_meta_data_Nekoxy__INekoxyClass, 0, 0, 0 }
};

void *INekoxyClass::qt_metacast(const char *_clname)
{
    if (!_clname) return 0;
    if (!strcmp(_clname, "Nekoxy::INekoxyClass"))
        return static_cast<void*>(const_cast<INekoxyClass*>(this));
    return QAxObject::qt_metacast(_clname);
}
static const uint qt_meta_data_Nekoxy__HttpProxy[] = {

 // content:
    7, // revision
    30,  // classname
    1, 14, // classinfo
    16, 16, // methods
    1, 158, // properties
    0, 0, // enums/sets
    0, 0, // constructors
    0, // flags
    3, // signal count

 // classinfo: key, value
    31, 32, 

// signal: name, argc, parameters, tag, flags
    1, 4, 96, 2, 5,
    7, 1, 105, 2, 5,
    9, 3, 108, 2, 5,

// slot: name, argc, parameters, tag, flags
    33, 1, 115, 2, 9,
    35, 0, 118, 2, 9,
    36, 0, 119, 2, 9,
    12, 2, 120, 2, 9,
    16, 1, 125, 2, 9,
    18, 1, 128, 2, 9,
    19, 1, 131, 2, 9,
    20, 1, 134, 2, 9,
    21, 1, 137, 2, 9,
    22, 2, 140, 2, 9,
    23, 0, 145, 2, 9,
    24, 3, 146, 2, 9,
    28, 2, 153, 2, 9,

// signal: parameters
    QMetaType::Void, QMetaType::Int, QMetaType::QString, QMetaType::QString, QMetaType::QString, 3, 4, 5, 6,
    QMetaType::Void, QMetaType::QString, 8,
    QMetaType::Void, QMetaType::QString, QMetaType::Int, QMetaType::VoidStar, 8, 10, 11,

// slot: parameters
    QMetaType::Bool, QMetaType::QVariant, 34,
    QMetaType::Int,
    0x80000000 | 37,
    QMetaType::Bool, 0x80000000 | 13, 0x80000000 | 13, 14, 15,
    QMetaType::Void, QMetaType::Int, 17,
    QMetaType::Void, QMetaType::Int, 17,
    QMetaType::Void, QMetaType::Int, 17,
    QMetaType::Void, QMetaType::Int, 17,
    QMetaType::Void, QMetaType::Int, 17,
    QMetaType::Void, QMetaType::QString, QMetaType::QString, 14, 15,
    QMetaType::Void,
    QMetaType::Void, QMetaType::Int, QMetaType::Bool, QMetaType::Bool, 25, 26, 27,
    QMetaType::Bool, 0x80000000 | 13, 0x80000000 | 13, 14, 15,

 // properties: name, type, flags
    38, QMetaType::QString, 0x0a005001, 		 // QString ToString

    0 // eod
};

const QMetaObject HttpProxy::staticMetaObject = {
{ &QObject::staticMetaObject,
qt_meta_stringdata_all.data,
qt_meta_data_Nekoxy__HttpProxy, 0, 0, 0 }
};

void *HttpProxy::qt_metacast(const char *_clname)
{
    if (!_clname) return 0;
    if (!strcmp(_clname, "Nekoxy::HttpProxy"))
        return static_cast<void*>(const_cast<HttpProxy*>(this));
    return QAxObject::qt_metacast(_clname);
}

