/****************************************************************************
**
** Metadata for Titanium_Web_Proxy generated by dumpcpp from type library
** e:\QTProject_GIT\a86b43fca89c33a2f703c0c6c7221cb8\TitaniumCOM\Titanium.Web.Proxy\bin\Release\Titanium.Web.Proxy.tlb
**
****************************************************************************/

#define QAX_DUMPCPP_TITANIUM_WEB_PROXY_NOINLINES
#include "titanium_web_proxy.h"

using namespace Titanium_Web_Proxy;

struct qt_meta_stringdata_all_t {
    QByteArrayData data[33];
    char stringdata0[377];
};
#define QT_MOC_LITERAL(idx, ofs, len, table) \
    Q_STATIC_BYTE_ARRAY_DATA_HEADER_INITIALIZER_WITH_OFFSET(len, \
    offsetof(qt_meta_stringdata_all_t, stringdata##table) + ofs \
        - idx * sizeof(QByteArrayData) \
    )
static const qt_meta_stringdata_all_t qt_meta_stringdata_all = {
    {
QT_MOC_LITERAL(0, 0, 34, 0),
QT_MOC_LITERAL(1, 35, 9, 0),
QT_MOC_LITERAL(2, 45, 0, 0),
QT_MOC_LITERAL(3, 46, 4, 0),
QT_MOC_LITERAL(4, 51, 6, 0),
QT_MOC_LITERAL(5, 58, 4, 0),
QT_MOC_LITERAL(6, 63, 4, 0),
QT_MOC_LITERAL(7, 68, 15, 0),
QT_MOC_LITERAL(8, 84, 4, 0),
QT_MOC_LITERAL(9, 89, 6, 0),
QT_MOC_LITERAL(10, 96, 4, 0),
QT_MOC_LITERAL(11, 101, 4, 0),
QT_MOC_LITERAL(12, 106, 23, 0),
QT_MOC_LITERAL(13, 130, 1, 0),
QT_MOC_LITERAL(14, 132, 16, 0),
QT_MOC_LITERAL(15, 149, 17, 0),
QT_MOC_LITERAL(16, 167, 15, 0),
QT_MOC_LITERAL(17, 183, 4, 0),
QT_MOC_LITERAL(18, 188, 14, 0),
QT_MOC_LITERAL(19, 203, 17, 0),
QT_MOC_LITERAL(20, 221, 8, 0),
QT_MOC_LITERAL(21, 230, 7, 0),
QT_MOC_LITERAL(22, 238, 13, 0),
QT_MOC_LITERAL(23, 252, 7, 0),
QT_MOC_LITERAL(24, 260, 31, 0),
QT_MOC_LITERAL(25, 292, 11, 0),
QT_MOC_LITERAL(26, 304, 14, 0),
QT_MOC_LITERAL(27, 319, 6, 0),
QT_MOC_LITERAL(28, 326, 3, 0),
QT_MOC_LITERAL(29, 330, 11, 0),
QT_MOC_LITERAL(30, 342, 7, 0),
QT_MOC_LITERAL(31, 350, 16, 0),
QT_MOC_LITERAL(32, 367, 8, 0)
    },
    "Titanium_Web_Proxy::ITitaniumClass\0exception\0\0code\0source\0disc\0help\0"
    "propertyChanged\0name\0signal\0argc\0argv\0SetAfterSessionComplete\0f\0SetBeforeRequest\0"
    "SetBeforeResponse\0SetMakecertPath\0path\0SetOnLogString\0SetOnNotification\0"
    "Shutdown\0Startup\0listeningPort\0control\0Titanium_Web_Proxy::ProxyServer\0"
    "Interface 1\0ITitaniumClass\0Equals\0obj\0GetHashCode\0GetType\0mscorlib::_Type*\0"
    "ToString\0"
};
#undef QT_MOC_LITERAL

static const uint qt_meta_data_Titanium_Web_Proxy__ITitaniumClass[] = {

 // content:
    7, // revision
    0,  // classname
    0, 0, // classinfo
    11, 14, // methods
    1, 110, // properties
    0, 0, // enums/sets
    0, 0, // constructors
    0, // flags
    3, // signal count

// signal: name, argc, parameters, tag, flags
    1, 4, 69, 2, 5,
    7, 1, 78, 2, 5,
    9, 3, 81, 2, 5,

// slot: name, argc, parameters, tag, flags
    12, 1, 88, 2, 9,
    14, 1, 91, 2, 9,
    15, 1, 94, 2, 9,
    16, 1, 97, 2, 9,
    18, 1, 100, 2, 9,
    19, 1, 103, 2, 9,
    20, 0, 106, 2, 9,
    21, 1, 107, 2, 9,

// signal: parameters
    QMetaType::Void, QMetaType::Int, QMetaType::QString, QMetaType::QString, QMetaType::QString, 3, 4, 5, 6,
    QMetaType::Void, QMetaType::QString, 8,
    QMetaType::Void, QMetaType::QString, QMetaType::Int, QMetaType::VoidStar, 8, 10, 11,

// slot: parameters
    QMetaType::Void, QMetaType::Int, 13,
    QMetaType::Void, QMetaType::Int, 13,
    QMetaType::Void, QMetaType::Int, 13,
    QMetaType::Void, QMetaType::QString, 17,
    QMetaType::Void, QMetaType::Int, 13,
    QMetaType::Void, QMetaType::Int, 13,
    QMetaType::Void,
    QMetaType::Void, QMetaType::Int, 22,

 // properties: name, type, flags
    23, QMetaType::QString, 0x0a055003, 		 // QString control

    0 // eod
};

const QMetaObject ITitaniumClass::staticMetaObject = {
{ &QObject::staticMetaObject,
qt_meta_stringdata_all.data,
qt_meta_data_Titanium_Web_Proxy__ITitaniumClass, 0, 0, 0 }
};

void *ITitaniumClass::qt_metacast(const char *_clname)
{
    if (!_clname) return 0;
    if (!strcmp(_clname, "Titanium_Web_Proxy::ITitaniumClass"))
        return static_cast<void*>(const_cast<ITitaniumClass*>(this));
    return QAxObject::qt_metacast(_clname);
}
static const uint qt_meta_data_Titanium_Web_Proxy__ProxyServer[] = {

 // content:
    7, // revision
    24,  // classname
    1, 14, // classinfo
    14, 16, // methods
    1, 132, // properties
    0, 0, // enums/sets
    0, 0, // constructors
    0, // flags
    3, // signal count

 // classinfo: key, value
    25, 26, 

// signal: name, argc, parameters, tag, flags
    1, 4, 86, 2, 5,
    7, 1, 95, 2, 5,
    9, 3, 98, 2, 5,

// slot: name, argc, parameters, tag, flags
    27, 1, 105, 2, 9,
    29, 0, 108, 2, 9,
    30, 0, 109, 2, 9,
    12, 1, 110, 2, 9,
    14, 1, 113, 2, 9,
    15, 1, 116, 2, 9,
    16, 1, 119, 2, 9,
    18, 1, 122, 2, 9,
    19, 1, 125, 2, 9,
    20, 0, 128, 2, 9,
    21, 1, 129, 2, 9,

// signal: parameters
    QMetaType::Void, QMetaType::Int, QMetaType::QString, QMetaType::QString, QMetaType::QString, 3, 4, 5, 6,
    QMetaType::Void, QMetaType::QString, 8,
    QMetaType::Void, QMetaType::QString, QMetaType::Int, QMetaType::VoidStar, 8, 10, 11,

// slot: parameters
    QMetaType::Bool, QMetaType::QVariant, 28,
    QMetaType::Int,
    0x80000000 | 31,
    QMetaType::Void, QMetaType::Int, 13,
    QMetaType::Void, QMetaType::Int, 13,
    QMetaType::Void, QMetaType::Int, 13,
    QMetaType::Void, QMetaType::QString, 17,
    QMetaType::Void, QMetaType::Int, 13,
    QMetaType::Void, QMetaType::Int, 13,
    QMetaType::Void,
    QMetaType::Void, QMetaType::Int, 22,

 // properties: name, type, flags
    32, QMetaType::QString, 0x0a005001, 		 // QString ToString

    0 // eod
};

const QMetaObject ProxyServer::staticMetaObject = {
{ &QObject::staticMetaObject,
qt_meta_stringdata_all.data,
qt_meta_data_Titanium_Web_Proxy__ProxyServer, 0, 0, 0 }
};

void *ProxyServer::qt_metacast(const char *_clname)
{
    if (!_clname) return 0;
    if (!strcmp(_clname, "Titanium_Web_Proxy::ProxyServer"))
        return static_cast<void*>(const_cast<ProxyServer*>(this));
    return QAxObject::qt_metacast(_clname);
}

