/****************************************************************************
**
** Namespace Titanium_Web_Proxy generated by dumpcpp from type library
** e:\QTProject_GIT\a86b43fca89c33a2f703c0c6c7221cb8\TitaniumCOM\Titanium.Web.Proxy\bin\Release\Titanium.Web.Proxy.tlb
**
****************************************************************************/

#ifndef QAX_DUMPCPP_TITANIUM_WEB_PROXY_H
#define QAX_DUMPCPP_TITANIUM_WEB_PROXY_H

// Define this symbol to __declspec(dllexport) or __declspec(dllimport)
#ifndef TITANIUM_WEB_PROXY_EXPORT
#define TITANIUM_WEB_PROXY_EXPORT
#endif

#include <qaxobject.h>
#include <qaxwidget.h>
#include <qdatetime.h>
#include <qpixmap.h>

struct IDispatch;


// Referenced namespace
namespace mscorlib {
    class _Type;
}


namespace Titanium_Web_Proxy {


class TITANIUM_WEB_PROXY_EXPORT ITitaniumClass : public QAxObject
{
public:
    ITitaniumClass(IDispatch *subobject = 0, QAxObject *parent = 0)
    : QAxObject((IUnknown*)subobject, parent)
    {
        internalRelease();
    }

    /*
    Method SetAfterSessionComplete
    */
    inline void SetAfterSessionComplete(int f);

    /*
    Method SetBeforeRequest
    */
    inline void SetBeforeRequest(int f);

    /*
    Method SetBeforeResponse
    */
    inline void SetBeforeResponse(int f);

    /*
    Method SetMakecertPath
    */
    inline void SetMakecertPath(const QString& path);

    /*
    Method SetOnLogString
    */
    inline void SetOnLogString(int f);

    /*
    Method SetOnNotification
    */
    inline void SetOnNotification(int f);

    /*
    Method Shutdown
    */
    inline void Shutdown();

    /*
    Method Startup
    */
    inline void Startup(int listeningPort);

// meta object functions
    static const QMetaObject staticMetaObject;
    virtual const QMetaObject *metaObject() const { return &staticMetaObject; }
    virtual void *qt_metacast(const char *);
};

// Actual coclasses
class TITANIUM_WEB_PROXY_EXPORT ProxyServer : public QAxObject
{
public:
    ProxyServer(QObject *parent = 0)
    : QAxObject(parent)
    {
        setControl("{7fd7b09d-b430-3b7f-95e0-a7e2bb8ba59b}");
    }

    ProxyServer(ITitaniumClass *iface)
    : QAxObject()
    {
        initializeFrom(iface);
        delete iface;
    }

    /*
    Property ToString
    */
    inline QString ToString() const; //Returns the value of ToString

    /*
    Method Equals
    */
    inline bool Equals(const QVariant& obj);

    /*
    Method GetHashCode
    */
    inline int GetHashCode();

    /*
    Method GetType
    */
    inline mscorlib::_Type* GetType();

    /*
    Method SetAfterSessionComplete
    */
    inline void SetAfterSessionComplete(int f);

    /*
    Method SetBeforeRequest
    */
    inline void SetBeforeRequest(int f);

    /*
    Method SetBeforeResponse
    */
    inline void SetBeforeResponse(int f);

    /*
    Method SetMakecertPath
    */
    inline void SetMakecertPath(const QString& path);

    /*
    Method SetOnLogString
    */
    inline void SetOnLogString(int f);

    /*
    Method SetOnNotification
    */
    inline void SetOnNotification(int f);

    /*
    Method Shutdown
    */
    inline void Shutdown();

    /*
    Method Startup
    */
    inline void Startup(int listeningPort);

// meta object functions
    static const QMetaObject staticMetaObject;
    virtual const QMetaObject *metaObject() const { return &staticMetaObject; }
    virtual void *qt_metacast(const char *);
};

// member function implementation
#ifndef QAX_DUMPCPP_TITANIUM_WEB_PROXY_NOINLINES
inline void ITitaniumClass::SetAfterSessionComplete(int f)
{
    void *_a[] = {0, (void*)&f};
    qt_metacall(QMetaObject::InvokeMetaMethod, 8, _a);
}

inline void ITitaniumClass::SetBeforeRequest(int f)
{
    void *_a[] = {0, (void*)&f};
    qt_metacall(QMetaObject::InvokeMetaMethod, 9, _a);
}

inline void ITitaniumClass::SetBeforeResponse(int f)
{
    void *_a[] = {0, (void*)&f};
    qt_metacall(QMetaObject::InvokeMetaMethod, 10, _a);
}

inline void ITitaniumClass::SetMakecertPath(const QString& path)
{
    void *_a[] = {0, (void*)&path};
    qt_metacall(QMetaObject::InvokeMetaMethod, 11, _a);
}

inline void ITitaniumClass::SetOnLogString(int f)
{
    void *_a[] = {0, (void*)&f};
    qt_metacall(QMetaObject::InvokeMetaMethod, 12, _a);
}

inline void ITitaniumClass::SetOnNotification(int f)
{
    void *_a[] = {0, (void*)&f};
    qt_metacall(QMetaObject::InvokeMetaMethod, 13, _a);
}

inline void ITitaniumClass::Shutdown()
{
    void *_a[] = {0};
    qt_metacall(QMetaObject::InvokeMetaMethod, 14, _a);
}

inline void ITitaniumClass::Startup(int listeningPort)
{
    void *_a[] = {0, (void*)&listeningPort};
    qt_metacall(QMetaObject::InvokeMetaMethod, 15, _a);
}


inline QString ProxyServer::ToString() const
{
    QVariant qax_result = property("ToString");
    Q_ASSERT(qax_result.isValid());
    return *(QString*)qax_result.constData();
}

inline bool ProxyServer::Equals(const QVariant& obj)
{
    bool qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&obj};
    qt_metacall(QMetaObject::InvokeMetaMethod, 8, _a);
    return qax_result;
}

inline int ProxyServer::GetHashCode()
{
    int qax_result;
    void *_a[] = {(void*)&qax_result};
    qt_metacall(QMetaObject::InvokeMetaMethod, 9, _a);
    return qax_result;
}

inline mscorlib::_Type* ProxyServer::GetType()
{
    mscorlib::_Type* qax_result = 0;
#ifdef QAX_DUMPCPP_MSCORLIB_H
    qRegisterMetaType<mscorlib::_Type*>("mscorlib::_Type*", &qax_result);
    qRegisterMetaType<mscorlib::_Type>("mscorlib::_Type", qax_result);
#endif
    void *_a[] = {(void*)&qax_result};
    qt_metacall(QMetaObject::InvokeMetaMethod, 10, _a);
    return qax_result;
}

inline void ProxyServer::SetAfterSessionComplete(int f)
{
    void *_a[] = {0, (void*)&f};
    qt_metacall(QMetaObject::InvokeMetaMethod, 11, _a);
}

inline void ProxyServer::SetBeforeRequest(int f)
{
    void *_a[] = {0, (void*)&f};
    qt_metacall(QMetaObject::InvokeMetaMethod, 12, _a);
}

inline void ProxyServer::SetBeforeResponse(int f)
{
    void *_a[] = {0, (void*)&f};
    qt_metacall(QMetaObject::InvokeMetaMethod, 13, _a);
}

inline void ProxyServer::SetMakecertPath(const QString& path)
{
    void *_a[] = {0, (void*)&path};
    qt_metacall(QMetaObject::InvokeMetaMethod, 14, _a);
}

inline void ProxyServer::SetOnLogString(int f)
{
    void *_a[] = {0, (void*)&f};
    qt_metacall(QMetaObject::InvokeMetaMethod, 15, _a);
}

inline void ProxyServer::SetOnNotification(int f)
{
    void *_a[] = {0, (void*)&f};
    qt_metacall(QMetaObject::InvokeMetaMethod, 16, _a);
}

inline void ProxyServer::Shutdown()
{
    void *_a[] = {0};
    qt_metacall(QMetaObject::InvokeMetaMethod, 17, _a);
}

inline void ProxyServer::Startup(int listeningPort)
{
    void *_a[] = {0, (void*)&listeningPort};
    qt_metacall(QMetaObject::InvokeMetaMethod, 18, _a);
}



#endif

}

QT_BEGIN_NAMESPACE

namespace QtMetaTypePrivate {
template<>
struct QMetaTypeFunctionHelper<Titanium_Web_Proxy::ITitaniumClass, /* Accepted */ true> {
    static void Delete(void *t) { delete static_cast<Titanium_Web_Proxy::ITitaniumClass*>(t); }
    static void *Create(const void *t)
    {
        Q_ASSERT(!t);
        Q_UNUSED(t)
        return new Titanium_Web_Proxy::ITitaniumClass();
    }
    static void Destruct(void *t)
    {
        Q_UNUSED(t)
        static_cast<Titanium_Web_Proxy::ITitaniumClass*>(t)->Titanium_Web_Proxy::ITitaniumClass::~ITitaniumClass();
    }
    static void *Construct(void *where, const void *t)
    {
        Q_ASSERT(!t);
        Q_UNUSED(t)
        return new (where) Titanium_Web_Proxy::ITitaniumClass;
    }
#ifndef QT_NO_DATASTREAM
    static void Save(QDataStream &stream, const void *t) { stream << *static_cast<const Titanium_Web_Proxy::ITitaniumClass*>(t); }
    static void Load(QDataStream &stream, void *t) { stream >> *static_cast<Titanium_Web_Proxy::ITitaniumClass*>(t); }
#endif // QT_NO_DATASTREAM
};

template<>
struct QMetaTypeFunctionHelper<Titanium_Web_Proxy::ProxyServer, /* Accepted */ true> {
    static void Delete(void *t) { delete static_cast<Titanium_Web_Proxy::ProxyServer*>(t); }
    static void *Create(const void *t)
    {
        Q_ASSERT(!t);
        Q_UNUSED(t)
        return new Titanium_Web_Proxy::ProxyServer();
    }
    static void Destruct(void *t)
    {
        Q_UNUSED(t)
        static_cast<Titanium_Web_Proxy::ProxyServer*>(t)->Titanium_Web_Proxy::ProxyServer::~ProxyServer();
    }
    static void *Construct(void *where, const void *t)
    {
        Q_ASSERT(!t);
        Q_UNUSED(t)
        return new (where) Titanium_Web_Proxy::ProxyServer;
    }
#ifndef QT_NO_DATASTREAM
    static void Save(QDataStream &stream, const void *t) { stream << *static_cast<const Titanium_Web_Proxy::ProxyServer*>(t); }
    static void Load(QDataStream &stream, void *t) { stream >> *static_cast<Titanium_Web_Proxy::ProxyServer*>(t); }
#endif // QT_NO_DATASTREAM
};

} // namespace QtMetaTypePrivate
QT_END_NAMESPACE

#endif

